name: Continuous Delivery
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build typescript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - run: yarn install

    - name: Compile code
      run: yarn build

    - name: Upload compiled code
      uses: actions/upload-artifact@v2
      with:
        name: ts-artifact
        path: lib/


  test:
    name: Test and Coverage
    needs: build
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: yarn install

    - name: Run Linter
      run: yarn lint

    - name: Run tests
      run: yarn test

    - name: Upload Coverage
      uses: codecov/codecov-action@v1


  publish:
    name: Publish to GitHub Package Registry
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download compiled code from build
      uses: actions/download-artifact@v2
      with:
        name: ts-artifact
        path: lib/

    - name: Set up Node.js for NPM
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn

    - name: Publish package to NPM
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up Node.js for GPR
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: Publish package to GPR
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
