name: Continuous Delivery
on: push

jobs:
  build:
    name: Build typescript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - run: yarn install

    - name: Compile code
      run: yarn build

    - name: Upload compiled code
      uses: actions/upload-artifact@v2
      with:
        name: ts-artifact
        path: lib/


  test:
    name: Test and Coverage
    needs: build
    runs-on: 'ubuntu-latest'
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: yarn install

    - name: Run Linter
      run: yarn lint

    - name: Run tests
      run: yarn test

    - name: Upload Coverage
      uses: codecov/codecov-action@v1


  publish:
    name: Publish to NPM & GitHub Package Registry
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main') # only run on main branch

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Check version changes
      uses: EndBug/version-check@v1
      id: check

    - name: Version update detected
      if: steps.check.outputs.changed == 'true'
      run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

    - name: Download compiled code from build
      uses: actions/download-artifact@v2
      if: steps.check.outputs.changed == 'true'
      with:
        name: ts-artifact
        path: lib/

    - name: Set up Node.js for NPM
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      if: steps.check.outputs.changed == 'true'
      run: yarn install

    - name: Publish package to NPM
      if: steps.check.outputs.changed == 'true'
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up Node.js for GPR
      if: steps.check.outputs.changed == 'true'
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'

    - name: Publish package to GPR
      if: steps.check.outputs.changed == 'true'
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
